- name: Reviewer lottery
  uses: uesteibar/reviewer-lottery@v2.0.0

groups:
  - name: Devs
    reviewers: 0 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - dzmitry-homza
      - dmitriy-homza
      - Veronika-Homza
