services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    ports:
      - 5433:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      net_backend:

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/opt/app
    networks:
      net_backend:

networks:
  net_backend:
    driver: bridge