export const subCategories = [
  // { name: 'При нарушениях кислотности', medications: [] },
  // { name: 'Спазмолитики и их комбинации', medications: [] },
  // { name: 'Противорвотные', medications: [] },
  // { name: 'Для печени и желчевыводящих путей', medications: [] },
  // { name: 'Слабительные', medications: [] },
  // { name: 'Противодиарейные', medications: [] },
  // { name: 'Для похудения', medications: [] },
  // { name: 'Ферменты', medications: [] },
  // { name: 'Для лечения сахарного диабета', medications: [] },
  // { name: 'Общетонизирующие', medications: [] },
  // { name: 'Другие (левокарнитин),{name:  тиоктовая кислота)', medications: [] },
  {
    name: 'Против боли в суставах и мышцах',
    medications: [
      {
        title: 'Кеторолак',
        description:
          'Нестероидный противовоспалительный препарат, эффективный анальгетик',
        price: 100,
        logo: 'https://lekpharm.by/assets/resized/464-419-fit-t/uploads/catalog/ketorolak/ketorolak-t-10-20.jpg',
      },
      {
        title: 'Диклофенак',
        description:
          'ДИКЛОФЕНАК относится к нестероидным противовоспалительным средствам (НПВС): оказывает противовоспалительное, обезболивающее и жаропонижающее действие. Ослабляет боль в покое и при движении, уменьшает воспалительный отёк, припухлость суставов, улучшает их функциональную способность.',
        price: 200,
        logo: 'https://pharmland.by/sites/default/files/product/dicl_50.jpg',
      },
      {
        title: 'Индометацин',
        description:
          'Круглые двояковыпуклые таблетки, покрытые пленочной оболочкой белого или почти белого цвета. На поперечном разрезе видны два слоя: ядро белого или белого с желтоватым оттенком цвета и пленочная оболочка.',
        price: 300,
        logo: 'https://f.stolichki.ru/s/drugs/medium/36/36464.jpg',
      },
      {
        title: 'Нимесулид',
        description:
          'Нимесулид оказывает противовоспалительное, анальгезирующее, жаропонижающее и антиагрегантное действие. Селективно подавляет ЦОГ2 и тормозит синтез простагландинов в очаге воспаления.',
        price: 450,
        logo: 'https://pharmland.by/sites/default/files/product/nimesulid_farmlend_100_mg_no20.jpg',
      },
      {
        title: 'Терафлекс',
        description:
          'Терафлекс – стимулирует регенерацию хрящевой ткани. Глюкозамин и хондроитина сульфат натрия принимают участие в синтезе соединительной ткани, способствуя предотвращению процессов разрушения хряща и стимулируя регенерацию ткани.',
        price: 500,
        logo: 'https://cdn.eapteka.ru/upload/offer_photo/206/838/1_58946cfc43dc778326e9cde7f9e56152.png?t=1653643547&_cvc=1686827238',
      },
    ],
  },
  { name: 'Против подагры', medications: [] },
  { name: 'Другие', medications: [] },
  { name: 'При заболеваниях сердца', medications: [] },
  // { name: 'При высоком давлении', medications: [] },
  // { name: 'Диуретики', medications: [] },
  // { name: 'Периферические вазодилататоры', medications: [] },
  // { name: 'При геморрое и анальных трещинах', medications: [] },
  // { name: 'При варикозном расширении вен', medications: [] },
  // { name: 'Для снижения проницаемости капилляров', medications: [] },
  // { name: 'Регуляторы обмена липидов', medications: [] },
  // { name: 'Антитромботические', medications: [] },
  // { name: 'Гемостатические', medications: [] },
  // { name: 'Антианемические', medications: [] },
  // { name: 'При заболеваниях носа', medications: [] },
  // { name: 'От кашля и простуды', medications: [] },
  // { name: 'При обструктивных заболеваниях', medications: [] },
  // { name: 'Другие', medications: [] },
  // { name: 'Антибиотики', medications: [] },
  // { name: 'Противовирусные', medications: [] },
  // { name: 'Противогрибковые', medications: [] },
  // { name: 'Противомикробные', medications: [] },
  // { name: 'Противовоспалительные', medications: [] },
  // { name: 'Комбинированные', medications: [] },
  // { name: 'Для лечения глаукомы', medications: [] },
  // { name: 'Противоаллергические', medications: [] },
  // { name: 'Прочие', medications: [] },
  // { name: 'Анестетики', medications: [] },
  // { name: 'Анальгетики', medications: [] },
  // { name: 'Успокаивающие', medications: [] },
  // { name: 'Антидепрессанты', medications: [] },
  // { name: 'Психостимуляторы и ноотропы', medications: [] },
  // { name: 'Для лечения деменции', medications: [] },
  // { name: 'При головокружении', medications: [] },
  // { name: 'Другие средства', medications: [] },
  // { name: 'Антисептики и противомикробные в гинекологии', medications: [] },
  // { name: 'Другие средства в гинекологии', medications: [] },
  // { name: 'При урологических заболеваниях', medications: [] },
  // { name: 'При аденоме простаты', medications: [] },
  // { name: 'Противогрибковые', medications: [] },
  // { name: 'Для лечения ран и язв', medications: [] },
  // { name: 'Для устранения зуда', medications: [] },
  // { name: 'Для лечения псориаза', medications: [] },
  // { name: 'Противомикробные', medications: [] },
  // { name: 'Гормональные', medications: [] },
  // { name: 'Антисептики и дезсредства', medications: [] },
  // { name: 'Для лечения угревой сыпи', medications: [] },
  // { name: 'Другие средства', medications: [] },
  // { name: 'Для щитовидной железы', medications: [] },
  // { name: 'Противопротозойные', medications: [] },
  // { name: 'Антигельминтные', medications: [] },
  // { name: 'Для уничтожения наружных паразитов', medications: [] },
];
